### ISSUE TITLE
Keymaster slots do not fully track date range changes

### ISSUE THREAD

**Issue by tykeal** [tykeal/homeassistant-rental-control#105]
It is possible that a date change will not be properly picked up by managed door slots. In theory they should self-correct at the midnight roll-over expiration of events. While this is true there is still the problem of the checkout time happening earlier in the day and the lock then becoming unavailable for potentially several hours before it corrects itself at midnight

**Comment by bigbroo2** [comment]
Your app is great! I would call it a lifesaver. Especially after Samsung and RLA issue. Do you have any plans fixing this bug? When guest extends the stay the code won't prolong?

**Comment by tykeal** [comment]
Oh, probably, at some point. It hasn't been a driving issue to me since the number of times I don't generally have to deal with more than one of these extensions at any one time / in large cases so it's not hard for me to do.

I welcome PRs, but I'll get to it eventually, I just don't know when :smile:
