### ISSUE TITLE
Last 4 Digits string

### ISSUE THREAD

**Issue by VerbalP** [tykeal/homeassistant-rental-control#141]
Hello,

In order to use the last 4 digits of  phone numbers as code, README states "event description contains 'Last 4 Digits' followed quickly by a 4 digit number"
https://github.com/tykeal/homeassistant-rental-control/blob/f73b9576264edcc877297f7df42243a76a0afee6/README.md#L38

Whereas, what's actually required in code is "(Last 4 Digits): " followed quickly by a 4 digit number
https://github.com/tykeal/homeassistant-rental-control/blob/1c888da3c56f798423810b29c254d3762f3337ed/custom_components/rental_control/sensors/calsensor.py#L81

Could "()" be made optional in that regex ?
`p = re.compile(r"""\(?Last 4 Digits\)?:\s+(\d{4})""")`

Could the README state that ": " is required?
`event description contains "(Last 4 Digits): " or "Last 4 Digits: " followed by a 4 digit number`

Regards,

**Comment by tykeal** [comment]
This has been fixed in v0.8.1
