### ISSUE TITLE
Integration Smoobu ?

### ISSUE THREAD

**Issue by nestor1832** [tykeal/homeassistant-rental-control#159]
First of all, thank you for your work.
I have been using it for several months to manage my reservations on AirBnb.
I have a request for an improvement :-)
Would it be possible to integrate the booking calendar of smoobu.com? (It is a company that integrates all booking portals)
It looks exactly like airBnb and I can easily provide you with the link to look at the ical file data.
Thank you very much for your answer.

**Comment by tykeal** [comment]
If you can provide me a link to a ical feed (send it to tykeal@bardicgrove.org) then I can see what is data it provides that other feeds currently do not and figure out what needs to happen to make it work well.

I do need an actual live link to be able to check it occasionally to see if they make changes to their feed data and to be able to validate that it's working by hooking it up to my test instance while doing the integration.

**Comment by nestor1832** [comment]
Hello Tykeal,
First of all, thank you for your reactivity.
As requested, I have emailed the Ical link to you.
I am at your disposal for further information, tests and others.
Great night

**Comment by tykeal** [comment]
Having looked over the ical that Smoobu provides, this is going to be a bit difficult. Events are apparently showing up 3 times. Once for checkin, once for checkout, and once covering the entire stay.

If you've got any configuration capabilities for the Ical, I would suggest turning off the checkin and checkout events if possible.

**Comment by tykeal** [comment]
@nestor1832 v0.9.0 now supports Smoobu
