### ISSUE TITLE
Unknown service "rental_control.update_code_slot"

### ISSUE THREAD

**Issue by kongjudas** [tykeal/homeassistant-rental-control#169]
I have never had this integration working with my ID-Locks but in the 2023.9 beta I get an error and the entire integration refuse to load. HA reports that **"rental_control.update_code_slot"** is an unknown service.

```
Logger: homeassistant.components.automation.rental_control_update_airbnb_startup_3
Source: helpers/script.py:420 
Integration: Automasjon (documentation, issues) 
First occurred: 12:29:01 (2 occurrences) 
Last logged: 12:29:01

Rental Control - Update Airbnb - startup: Counted slot update: Error executing script. Service not found for call_service at pos 1: Unable to find service rental_control.update_code_slot
Rental Control - Update Airbnb - startup: Error executing script. Service not found for repeat at pos 2: Unable to find service rental_control.update_code_slot
```

**Comment by kongjudas** [comment]
I had to delete a few files that were stuck in /packages/rental_control and downgrade to 2023.8.4 to get it back up. I've tried all in my power to get this working with 2023.9 (beta) but no success. This issue can be closed.

**Comment by tykeal** [comment]
This is definitely a bug! I just upgraded my test instance to 2023.9 since it released and it's giving me the same error.

**Comment by tykeal** [comment]
The actual culprit will have to do with this traceback:

```
2023-09-06 16:01:10.436 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry REDACTED for rental_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rental_control/__init__.py", line 107, in async_setup_entry
    hass.data[DOMAIN][entry.unique_id] = RentalControl(
                                         ^^^^^^^^^^^^^^
  File "/config/custom_components/rental_control/__init__.py", line 367, in __init__
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 531, in async_get_or_create
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Can't link device to unknown config entry REDACTED```

**Comment by freshfieldx** [comment]
Just to confirm I'm also experiencing this after upgrading.
I appreciate you already looking at it.

**Comment by kongjudas** [comment]
It doesn't do anything for me, except showing the dates. I always have to add door codes manually. That's why I closed it, to avoid nagging about something that could be on my setup only (ID-Lock 150 z-wave).

**Comment by freshfieldx** [comment]
but doesn't the integration fail to setup on restart?

**Comment by kongjudas** [comment]
> but doesn't the integration fail to setup on restart?

After upgrading to HA 2023.9 it fails immediately. I downgraded to 2023.8 again and had to delete three files in the /packages/rental_control folder before I reinstalled it. So I'm on 2023.8.4 now.

**Comment by tykeal** [comment]
@freshfieldx yes the integration fails to properly init on a restart of HA. It's failing early enough in the setup that nothing works.

I believe I'v tracked the issue down to the likely culprit in home-assistant/core#98157 due to how the device is being built up during the initialization.

**Comment by tykeal** [comment]
Release v0.9.2 fixes this and is also backwards compatible to older versions of HA :)

**Comment by kongjudas** [comment]
Thank you! It works like a charm now :)

**Comment by freshfieldx** [comment]
[like]  Brian Rainey reacted to your message:
________________________________
