### ISSUE TITLE
Set slot names to the guest's name rather than confirmation #

### ISSUE THREAD

**Issue by KevinDosi** [tykeal/homeassistant-rental-control#177]
I think this would be a great feature, because the guest's name means a lot more to me than the confirmation #. But is there a way to do this if it won't be built into the integration?

**Comment by tykeal** [comment]
@KevinDosi  Sorry, I missed seeing this issue being opened as I was on a business trip. Are you using Airbnb? The integration uses the guest name if it can get it from the calendar entry. In  the case of Airbnb, that information is not available and as such the reservation ID is used as it's the only globally unique piece of information available in the calendar entry.

It's possible to get the guest name in RC information from Airbnb, but you have to be using another service like Guesty which has direct API access to Airbnb and can therefore rexport the calendar entries with more details.
