### ISSUE TITLE
Integration with auth provider command_line

### ISSUE THREAD

**Issue by reydecopas** [tykeal/homeassistant-rental-control#178]
Great project!!!

Would it be possible to integrate the authentication provider with command_line script?
The same way that changes codes for keymaster lock... could it change a script to allow the user to login during the booking time of the property base on same parameters?

**Comment by tykeal** [comment]
@reydecopas you can automate this yourself based upon the calendar entity that is created and pulling data from the related sensor.

Personally, I would recommend against granting your guests direct access to your Home Assistant. You could investigate using the [Limited Guest addon](https://github.com/TekniskSupport/homeassistant-addons) for a way to provide limited access to certain things for your guests. I've used that a few times to provide access to garage doors, but I don't do it in an automated fashion as I've only provided it for medium - long term guests.
