### ISSUE TITLE
Block bookings not showing

### ISSUE THREAD

**Issue by thechrislewis** [tykeal/homeassistant-rental-control#182]
I have airbnb calendar imported, but a block booking of 3 days is not highlighted on month view, only first date. The calendar correctly shows room as reserved for each subsequent date in day view.

**Comment by tykeal** [comment]
I'm not following the comment here. Month view of what?

**Comment by thechrislewis** [comment]
Don't worry.  One update of HA later and all working as it should.
Most likely browser caching. Sorry for inconvenience
