### ISSUE TITLE
Combined Event Sensor 

### ISSUE THREAD

**Issue by freshfieldx** [tykeal/homeassistant-rental-control#184]
Firstly, great work.

Is it possible to have a list of events from more than one calendar? So we have AirBNB and Other calendars, but we would like a list of upcoming bookings from both sources.

Thanks

**Comment by tykeal** [comment]
The complexity of doing something like that is definitely not what I want to support. I would suggest that if you want a single combined calendar that you investigate one of the platforms out there such as Guesty that can do that for you. Unfortunately, those platforms do cost some some for each unit being added. But, you get a single calendar output from them that can then be consumed by this integration.

Alternatively, the code is open, if you want to propose changes that would make this workable, I would be willing to review them and possibly merge it.

If you don't want to go that route, then I would suggest you add multiple instances of the integration against each of the calendars. If you're controlling locks via Keymaster, then make sure that the slots being managed do not overlap.

You can then view all the calendars in one place using something like the Atomic Calendar Revive Lovelace card.

While all of my units are via Airbnb I have several units all in one house (I'm letting out spare rooms in my house) so I've got the integration configured multiple times on my home HA instance. Once for the front door for each guest room and _another_ time for each guest room for their individual locks. I have my atomic calendar configured to show me just a single instance of each of the rooms but it's easy to read that way.

For example, here's what mine looks like right now in the event mode vs calendar mode that I prefer it in:

![Screenshot 2024-04-26 at 13-45-30 Rental Control – H7925](https://github.com/tykeal/homeassistant-rental-control/assets/1143598/0e35328f-1e21-4057-b6bd-d3ba43e602b4)

**Comment by freshfieldx** [comment]
Thanks for the update and suggestion. I will take a look at Atomic as your screenshot is the type of thing I wanted.
