### ISSUE TITLE
Lock code did not update when guest made reservation change

### ISSUE THREAD

**Issue by shwarnock** [tykeal/homeassistant-rental-control#219]
Hello, and thanks for the awesome integration. The issue I had is as follows:

1. Guest booked my room
2. Rental Control created a door code for the guest as they were checking in 1 day in the future.
3. After the guest had booked the room, and before they checked in, they asked to update their reservation and checkin a day earlier.
4. We approved the change request.

The calendar imported into HA was updated properly and showed an event that started on their new checkin day. However, their created lock code was not updated to reflect their new check-in day. We use the `2 digit check-in day and 2 digit check-out day` as the guest codes. I would expect Rental Control to update the guest code to reflect the new check-in days. Maybe we don't want that to happen if the guest has already checked in and they extend their stay longer because then we would need to message the guest a new code, but if the guest makes a change before checking in, I would expect the code to update to their new checkin and check out day because we have automatic messages that get sent out that expect the code to match their reservation.

**Comment by tykeal** [comment]
RC doesn't make changes to codes once they're assigned to a slot. This is to help protect against codes changing after a guest has arrived or after possible messaging to the guest.

I'm willing to evaluate a PR for a mechanism to allow RC to always make code changes, or at least prior to guest check-in, but I personally see very little reason to do this.

In general I suggest using phone numbers if possible as they are the most stable data for codes.

**Comment by shwarnock** [comment]
I use lodgify as my channel manager, and I don't think the events supplied by the iCal from Lodgify include the phone number or email unforutantely.

**Comment by tykeal** [comment]
If you email me ( tykeal@bardicgrove.org ) a working ICS URL I can take a look and see if there is data that is available that RC isn't currently capturing. That's how we've learned support for everything except Airbnb, which I use, and custom calendars, which I also use but is easy to create / test even if I didn't.

**Comment by shwarnock** [comment]
Sounds good, I will send it over. I took a look, and I don't really see anything that would be useful. It looks like the strip the Description field completely. I have been working on some local changes that allow to toggle in the config an  option to update the slot code ONLY IF, the checkin date of the reservation is after the current date. I will try to put in into PR tomorrow, but this is my first time trying to do a pull request with HA and I am not really sure how to setup a debugger to remotely connect to it, so Im really working on just trial and error, but it does seem to be working properly.

**Comment by tykeal** [comment]
Thanks for the ICS link. You're right. They really don't give you much information.

As for debugging, the _best_ way is to make sure you put in debugging LOGGER statements (see the code you'll see them peppered around) and then turn up the logging in HA to output the debugging statements. You can then follow the `~/config/home-assistant.log` file if you're using Home Assistant OS.

**Comment by tykeal** [comment]
Also, you may notice that I don't have any unit tests. I haven't figured out how to do them sanely given the weird live calendar requirements and not having a good way to mock it, along with having to figure out a way to mock Keymaster integration!

**Comment by shwarnock** [comment]
> Thanks for the ICS link. You're right. They really don't give you much information.
> 
> As for debugging, the _best_ way is to make sure you put in debugging LOGGER statements (see the code you'll see them peppered around) and then turn up the logging in HA to output the debugging statements. You can then follow the `~/config/home-assistant.log` file if you're using Home Assistant OS.

This is exactly what I was doing, but I was hoping to be able to attach a debugger like Visual Studio Code to the process and step through the code a bit. Doing it the way you mentioned was enough to get what I needed to though.

**Comment by shwarnock** [comment]
One quick question, is there a way to conditionally display options in a config schema? I see you are using both Optional and Required, but wondering if I can display my new toggle box only if `Door Code Generator` is set to `StartDate/EndDate`
