### ISSUE TITLE
Add a simple example usage of Rental Control to the instructions

### ISSUE THREAD

**Issue by infrachris** [tykeal/homeassistant-rental-control#229]
Show an example of automating something based on a tenant check-in.  I use the word 'automation' broadly and not as a specific home assistant definition.  An example of what one is most likely to automate (guest checking in, turn something on an hour before) would serve everyone really well.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add a new function to create an automation that turns on the HVAC system an hour before guest check-in. This function will be called during the package generation process.

You can review changes in this commit: https://github.com/lkilu6456546/tykeal-homeassistant-rental-control-229/commit/5dcc75eb10f6fdab327f8f8a4e0c52feb206be86.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by tykeal** [comment]
@infrachris a basic automation based on my real usage (though mine is more complex) has been added to the docs. for you in #232
