### ISSUE TITLE
Codes aren't added/deleted properly

### ISSUE THREAD

**Issue by shwarnock** [tykeal/homeassistant-rental-control#230]
Not sure if this is going to be rental control or keymaster, but I had ilnstances where codes enabled/disabled via rental control gets stuck in that state and never updates to disconnected/connected. Let me know how I can help you with this issue. If it sounds like Keymaster, I can open a ticket there. Cheers!

**Comment by tykeal** [comment]
@shwarnock this is definitely a Keymaster issue. Rental Control doesn't actually push the codes to the locks, it relies on Keymaster to do it. There are several different issues raised against Keymaster related to this and it's a known issue but the devs haven't found a definitive fix for it :(
