### ISSUE TITLE
Change naming of "Reservation URL" and "Phone Number (Last 4 Digits)" attributes

### ISSUE THREAD

**Issue by true-bluey** [tykeal/homeassistant-rental-control#94]
Suggestion to change names of attributes within "Description" to make for easier parsing and to better conform to JSON standards

**Comment by tykeal** [comment]
I'm not certain what you're asking here. If you're talking about an AirBnB calendar that you've got, then the description line literally is:

`Reservation URL: <some URL>\nPhone Number (Last 4 Digits): ????`

Other calendar providers have different description lines. For instance, from the various calendars that others have provided to me I can see that

* VRBO doesn't set a description line at all
* Guesty gives differing information depending on the backend sources. I've seen AirBnB descriptions, but also descriptions that look like: `Phone Number(Last 4 Digits): ????\nPhone Number: <phone_number>\nEmail: <email>`
* TripAdvisor seems to shove the checkin and out dates into the description along with the property description and a URL to the reserveration

In any case, the integration is not at present, and not likely to go mucking with the description information as it's pretty much a free-for-all from the various platform providers out there. I'm comfortable with the prefixing to the Summary as that has to be a single line per the iCal standards.

**Comment by true-bluey** [comment]
Ah. Didn't realise description came directly from the source. 

For now I've parsed out the URL and Phone Number/PIN from the description using RegEx.

**Comment by tykeal** [comment]
Are you needing the last 4 for something (like door codes?) If so, then make sure you set the code generator in the config to 'Last 4 Phone Digits' and not the default 'Start/End Date' if you do that you can get the last 4 out of the 'Slot Code' attribute of the sensor

**Comment by true-bluey** [comment]
I'm using the last 4 for a door code, but I'm using the main rental_control_xxx rather than rental_control_xxx_event_0. I hadn't noticed that the attributes for the two are different. Is there a reason for that?

**Comment by tykeal** [comment]
By "main" rental_control_xxx do you mean the calendar entity? The reason for them being different is that the eventual end goal for the integration is to directly manage a door lock by way of Keymaster in the future. At least at my rentals I regularly have some overlap of schedules so the individual events are where the primary logic for code management lives. The calendar entity is mostly designed with the idea of showing you a calendar view of up coming events (I use Atomic Calendar Revive for that as it's got a great schedule view)

**Comment by true-bluey** [comment]
Yes, I was referencing the calendar, rather than the sensor entity. 

I only have one rental, so no conflict, but I'll move to the sensor to future proof (and so I can stop having to parse out the PIN/phone number). I'll still need to parse out the URL as I use it as a convenience feature to click from a chip to the next reservation.

**Comment by tykeal** [comment]
I see. I think I have an idea on how to do this in a way that isn't going to get super silly. Let me try some things

**Comment by tykeal** [comment]
@true-bluey next release will have the data extracted for you attached to the sensor. Since it sounds like you're doing Airbnb you'll get a reservation_url and last_four attribute attached to your event sensor if the data exists, which it should if it's an actual booking and not a **'Not available'** or **'Blocked'** ;)
